package carrental;
// Generated Apr 28, 2018 6:37:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Booking generated by hbm2java
 */
public class Booking  implements java.io.Serializable {


     private Integer id;
     private Cars cars;
     private Users users;
     private Date bookingDate;
     private Date pickDate;
     private Date dropDate;

    public Booking() {
    }

    public Booking(Cars cars, Users users, Date bookingDate, Date pickDate, Date dropDate) {
       this.cars = cars;
       this.users = users;
       this.bookingDate = bookingDate;
       this.pickDate = pickDate;
       this.dropDate = dropDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cars getCars() {
        return this.cars;
    }
    
    public void setCars(Cars cars) {
        this.cars = cars;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getBookingDate() {
        return this.bookingDate;
    }
    
    public void setBookingDate(Date bookingDate) {
        this.bookingDate = bookingDate;
    }
    public Date getPickDate() {
        return this.pickDate;
    }
    
    public void setPickDate(Date pickDate) {
        this.pickDate = pickDate;
    }
    public Date getDropDate() {
        return this.dropDate;
    }
    
    public void setDropDate(Date dropDate) {
        this.dropDate = dropDate;
    }




}


