package carrental;
// Generated Apr 28, 2018 6:37:44 PM by Hibernate Tools 4.3.1


import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.Hibernate;

/**
 * Cars generated by hbm2java
 */
public class Cars  implements java.io.Serializable {


     private int reg;
     private String model;
     private String type;
     private int rent;
     private String availability;
     private byte[] image;
     private Set<Booking> bookings = new HashSet<Booking>(0);

    public Cars() {
    }

	
    public Cars(int reg, String model, String type, int rent, String availability, byte[] image) {
        this.reg = reg;
        this.model = model;
        this.type = type;
        this.rent = rent;
        this.availability = availability;
        this.image = image;
    }
    public Cars(int reg, String model, String type, int rent, String availability, Set<Booking> bookings) {
       this.reg = reg;
       this.model = model;
       this.type = type;
       this.rent = rent;
       this.availability = availability;
       this.bookings = bookings;
    }
   
    public int getReg() {
        return this.reg;
    }
    
    public void setReg(int reg) {
        this.reg = reg;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public int getRent() {
        return this.rent;
    }
    
    public void setRent(int rent) {
        this.rent = rent;
    }
    public String getAvailability() {
        return this.availability;
    }
    
    public void setAvailability(String availability) {
        this.availability = availability;
    }
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }
    
     public byte[] getImage() {
    return this.image;
  }
  public void setImage(byte[] image) {
    this.image = image;
  }
  @SuppressWarnings("unused")
  private void setBlob(Blob imageBlob) {
    this.image = toByteArray(imageBlob);
  }
  @SuppressWarnings("unused")
  private Blob getBlob(){
    return Hibernate.getLobCreator(HibernateUtil.getSessionFactory().getCurrentSession()).createBlob(this.image);
  }
  private byte[] toByteArray(Blob fromImageBlob) {
    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    try {
      return toByteArrayImpl(fromImageBlob, baos);
    } catch (Exception e) {
    }
    return null;
  }

  private byte[] toByteArrayImpl(Blob fromImageBlob,
      ByteArrayOutputStream baos) throws SQLException, IOException {
    byte buf[] = new byte[4000];
    int dataSize;
    InputStream is = fromImageBlob.getBinaryStream();

    try {
      while((dataSize = is.read(buf)) != -1) {
        baos.write(buf, 0, dataSize);
      }
    } finally {
      if(is != null) {
        is.close();
      }
    }
    return baos.toByteArray();
  }




}


